### ISSUE TITLE
捣个乱

### ISSUE THREAD

**Issue by nay-kang** [yy-shi/mysql-reader#1]
1,public下面的php_erros.log文件没有ignore，还有建议移到其他目录下
2,处理url，建议用php内置的parse_url和parse_str
3,类里面的一些私有变量不需要改变的，建议用const
4,configer这个类，如果是"config1.config2.config3"这种用“点”进行层级读去的方式更精简，另外利用“->”这种方式进行读取，总给人一种不安全感，感觉随时可能抛出异常，eg:Configer::single()->config('query.rowMax')
5,分隔多条查询语句貌似有点难度，比如"select \* from oc_order where user_agent like 'stylewe;mse 10;chrome 47' ",还有myql关键字delimiter也要注意哦
6,在写log的时候，是不是忘记加用户信息了？
7,auth里面的_expire是不是没有用上？_cookieName名字有点和他的本身意义不匹配，这里用的是sessionName

**Comment by 4-1-1** [comment]
1. php_error 是改了php.ini配置出现的 ，然后忘记ignore，现已删除，并添加ignore
2. ok,已修改
3. 目测只有auth类，有不需要改变的私有变量， 是设计的时候想做成可配置的，后来觉得没必要
4. 不会抛异常 返回false， 可以支持两种调用方法,如configer::config('ldap.host');
5. 有点难度， 可以解决，delimiter不是问题，因为只会执行select show set开头的语句
6. 有用户信息
7. sessionObj _expire确实没有用，session_start在index里 没有指定时间，已删除
