### ISSUE TITLE
html转义问题

### ISSUE THREAD

**Issue by nay-kang** [yy-shi/mysql-reader#2]
如果数据库中的内容是html转义后的，希望按照原样展示，不要反转移，这样无法确切的得知数据库里面存的内容。

**Comment by 4-1-1** [comment]
已经修复
https://github.com/yy-shi/mysql-reader/commit/e10b165bc74be6c38b2694df0473aabfb0c92ff3

**Comment by nay-kang** [comment]
<br />
<b>Notice</b>:  Use of undefined constant htmlspecialchars - assumed 'htmlspecialchars' in <b>/data/www/mysql-reader-master/public/index.php</b> on line <b>106</b><br />
